version: '3.8'

services:
  app:
    container_name: drughub_app
    image: ${DOCKER_IMAGE_BACKEND:-drughub.microservices:latest}
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - drughub_network

  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - drughub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"
    container_name: redis_db
    networks:
      - drughub_network

volumes:
  postgres_data:

networks:
  drughub_network:
    driver: bridge
