"""drop password field

Revision ID: 9baa9215e55d
Revises: 854c111ebb59
Create Date: 2025-04-11 20:55:49.237997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9baa9215e55d'
down_revision: Union[str, None] = '854c111ebb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
